#!/usr/bin/env python3

import os
import shutil

# Root of the installation
prefix = "/usr/local"

# Root of the executables
exec_prefix = prefix

# Executables
bindir = os.path.join(exec_prefix, "bin")

# Project specific absolute path
srcdir = os.path.abspath(os.path.dirname(__file__))

green = "\033[32m"
blue = "\033[34m"
bold = "\033[1m"
reset = "\033[0m"


def install():
    installdirs()
    print(f"{blue}Installing ...{reset}")
    shutil.copy(os.path.join(srcdir, "radm"), os.path.join(bindir, "radm"))
    print(f"   Installing {green}radm{reset} in {green}{os.path.join(bindir, 'radm')}")
    print(f"{blue}Installing{reset} {green}DONE{reset}")


def installdirs():
    print(f"{blue}Creating directories ...{reset}")
    os.makedirs(bindir, exist_ok=True)
    print(f"   Creating directory {green}{bindir}{reset}")
    print(f"{blue}Creating directories{reset} {green}DONE{reset}\n")


def uninstall():
    os.remove(os.path.join(bindir, "radm"))


if __name__ == "__main__":
    install()
